package com.abrarshakhi.lumen.core.data.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import android.util.Base64

/**
 * AES-256-GCM encryption backed by the Android Keystore.
 *
 * Written directly against `javax.crypto` rather than using a library:
 * `androidx.security-crypto` is deprecated with no replacement, and Tink's
 * `AndroidKeysetManager` is the thing it wrapped — a dependency to solve a problem that is
 * about eighty lines of standard JCA.
 *
 * The key never leaves the Keystore; only ciphertext is persisted. GCM provides
 * authenticated encryption, so tampering is detected rather than silently decrypting to
 * garbage.
 */
class KeystoreSecretCipher {

    class DecryptionFailed(message: String, cause: Throwable?) : Exception(message, cause)

    fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())

        // The IV is generated by the cipher, never chosen by us: reusing an IV under GCM
        // is catastrophic, and letting the provider supply it removes that whole class of
        // mistake.
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

        return "${iv.encode()}$SEPARATOR${ciphertext.encode()}"
    }

    fun decrypt(envelope: String): String {
        val parts = envelope.split(SEPARATOR)
        if (parts.size != 2) throw DecryptionFailed("Malformed secret envelope", null)

        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                secretKey(),
                GCMParameterSpec(TAG_LENGTH_BITS, parts[0].decode()),
            )
            String(cipher.doFinal(parts[1].decode()), Charsets.UTF_8)
        } catch (cause: Exception) {
            // Covers a rotated or invalidated key and any tampering GCM detects. The caller
            // must treat this as "the secret is gone", not retry.
            throw DecryptionFailed("Stored secret could not be decrypted", cause)
        }
    }

    /** Drops the key, rendering every existing envelope permanently unreadable. */
    fun resetKey() {
        runCatching { keyStore().deleteEntry(KEY_ALIAS) }
    }

    private fun secretKey(): SecretKey {
        val existing = keyStore().getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
        existing?.secretKey?.let { return it }
        return generateKey()
    }

    private fun generateKey(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)

        fun spec(strongBox: Boolean) = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            .setRandomizedEncryptionRequired(true)
            // Deliberately NOT setUserAuthenticationRequired: Lumen is summoned constantly,
            // and demanding a biometric before every launch would make it unusable.
            .apply { if (strongBox) setIsStrongBoxBacked(true) }
            .build()

        return try {
            generator.init(spec(strongBox = true))
            generator.generateKey()
        } catch (_: StrongBoxUnavailableException) {
            // Most mid-range devices have no StrongBox; falling back to the TEE-backed
            // keystore is correct, and failing here would be absurd.
            generator.init(spec(strongBox = false))
            generator.generateKey()
        } catch (_: Exception) {
            generator.init(spec(strongBox = false))
            generator.generateKey()
        }
    }

    private fun keyStore(): KeyStore =
        KeyStore.getInstance(PROVIDER).apply { load(null) }

    private fun ByteArray.encode(): String = Base64.encodeToString(this, Base64.NO_WRAP)

    private fun String.decode(): ByteArray = Base64.decode(this, Base64.NO_WRAP)

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "lumen.secrets.v1"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val TAG_LENGTH_BITS = 128
        const val SEPARATOR = ":"
    }
}
